name: Flatcoin keeper Dev Competition

on:
  workflow_dispatch:
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        name: Setup node
        with:
          node-version: 16
          cache: "yarn"
          
      - run: yarn install --frozen-lockfile
        name: Install dependencies
        
      - name: Build application
        run: yarn nest build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: dhedge/flatcoin-order-keeper
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Get package version
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          # file: ./Dockerfile
          push: true
          tags: dhedge/flatcoin-order-keeper:${{ steps.get-version.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Connect to Server and Deploy
        uses: appleboy/ssh-action@v1.0.0
        env: 
          PACKAGE_VERSION: ${{ steps.get-version.outputs.version }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          envs: PACKAGE_VERSION
          script: |
            docker-compose stop flatcoin-orderkeeper-competition
            export flatcoinOrderKeeperVersion=$PACKAGE_VERSION
            docker-compose pull flatcoin-order-keeper
            docker-compose up -d flatcoin-order-keeper-competition
